ktor {
  application {
    modules = [ org.example.ApplicationKt.module ]
  }

  deployment {
    port = 8080
    port = ${?PORT}
    host = "0.0.0.0"
    host = ${?HOST}
  }
}

security {
  jwt {
    secret = ${?JWT_SECRET}
    issuer = "auth-api"
    issuer = ${?JWT_ISSUER}
    audience = "auth-api-users"
    audience = ${?JWT_AUDIENCE}
    realm = "access-to-auth-api"
    realm = ${?JWT_REALM}
    expiresInMs = 86400000
    expiresInMs = ${?JWT_EXPIRES_MS}
  }

  super {
    key = ${?SUPER_KEY}
  }
}

storage {
  sqlite {
    path = "data/app.db"
    path = ${?SQLITE_PATH}
  }
}
